// Generated by Wrangler by running `wrangler types`

interface Env {
	PROXY_TARGET: "https://www.mintminds.com";
	GROWTHBOOK_API_HOST: "https://cdn.growthbook.io";
	GROWTHBOOK_CLIENT_KEY: "sdk-eJC0qCGZjxZPg5X";
}
