// Generated by Wrangler by running `wrangler types`

interface Env {
	PROXY_TARGET: "https://www.wijkraadzuidoostenschede.nl";
	GROWTHBOOK_API_HOST: "https://cdn.growthbook.io";
	GROWTHBOOK_CLIENT_KEY: "sdk-eJC0qCGZjxZPg5X";
	GROWTHBOOK_TRACKING_CALLBACK: "(experiment, results) => { console.log('browser tracking callback', {experiment, results}); }";
}
